CC=g++

SRCDIR=./src
TGTDIR=$(SRCDIR)/targets/$(TGT)

BINDIR=./bin
INCDIRS=-I$(TGTDIR) -I$(SRCDIR) -I/usr/local/include/libbson-1.0 -I/usr/local/include/libmongoc-1.0 

FLAGS=-g -rdynamic -Wall -Wno-write-strings --std=c++11

LIBS=-lcurl -lmicrohttpd -ljsoncpp -lpthread -lmongoc-1.0 -lbson-1.0 -lz -lcrypto -pthread
OPTS=

COMMSRC= $(SRCDIR)/types/*.cpp \
	$(SRCDIR)/utils/*.cpp \
	$(SRCDIR)/database/*.cpp \
	$(SRCDIR)/http/*.cpp \
	$(SRCDIR)/Module/*.cpp \



