#ifndef SRC_UTILS_ERROR_H_
#define SRC_UTILS_ERROR_H_

class Error{
public:
	enum ErrorType{
		NO_ERROR = 1,
		INVALID_FUNCTION_PTR = -300,
		INVALID_SOCK_ID = -100,
		INVALID_PORT_NUM = -101,
		INVALID_PARAM = -200,
		INVALID_CONFIG_STR = -400,
		NO_HTTP_SERVER = -500,

		DOCKER_API_ERROR,

		ERROR_PARSING = -700,
		NOT_FOUND = -701,

		LINK_CRAWLER_DOWNLOAD_ERROR = -1001,
		LINK_CRAWLER_PARSE_ERROR = -1002,
		LINK_CRAWLER_OK = -1003,

		INVALID_PEER_ID = -2000,
		ERROR_WRITING_TO_SOCKET = -2001

	};

private:

};

#endif
